"""Project data model — mirrors the web app's state so we can port logic 1:1."""
from __future__ import annotations
from dataclasses import dataclass, field
import itertools

_ids = itertools.count(1)


def uid(prefix="e") -> str:
    return f"{prefix}{next(_ids)}"


@dataclass
class Event:
    lane_id: str
    beat: float
    vel: float = 0.85
    length: float = 0.0          # sustain length in beats (0 = one-shot)
    pitch: int | None = None
    tune: int = 0                # per-note pitch offset in semitones
    src_t: float | None = None   # position in the original take (s)
    src_dur: float | None = None
    eq: dict = field(default_factory=lambda: {"low": 0, "mid": 0, "high": 0})
    id: str = field(default_factory=lambda: uid("e"))


@dataclass
class Lane:
    kind: str = "drum"           # drum | synth | sample | master
    sound: str = "snare"
    name: str = "Sound"
    muted: bool = False
    solo: bool = False
    auto: bool = False           # was auto-generated by extraction
    has_original: bool = False   # a real master take is available to play back
    play_original: bool = False  # play the real recording slice instead of the instrument
    src_master: str | None = None
    eq: dict = field(default_factory=lambda: {"low": 0, "mid": 0, "high": 0})
    id: str = field(default_factory=lambda: uid("R"))

    @property
    def tag(self) -> str:
        return self.id

    @property
    def subtitle(self) -> str:
        return f"{self.kind.upper()} · NO RECORDING"


@dataclass
class Project:
    lanes: list[Lane] = field(default_factory=list)
    events: list[Event] = field(default_factory=list)
    bpm: int = 90
    grid: int = 4                # subdivisions per beat for snapping
    start_at: float = 0.0
    metronome: bool = False
    loop_on: bool = False
    loop_start: float | None = None
    loop_end: float | None = None

    def lane_index(self, lane_id: str) -> int:
        for i, l in enumerate(self.lanes):
            if l.id == lane_id:
                return i
        return -1

    def events_for(self, lane_id: str):
        return [e for e in self.events if e.lane_id == lane_id]

    def max_beat(self) -> float:
        m = 0.0
        for e in self.events:
            m = max(m, e.beat + (e.length or 0))
        return m

    def snap(self, beat: float) -> float:
        g = self.grid or 4
        return max(0.0, round(beat * g) / g)


def empty_project() -> Project:
    """A clean grid with a few ready-to-record tracks and no beats."""
    p = Project(bpm=90)
    for kind, sound, name in (("drum", "kick", "Kick"), ("drum", "snare", "Snare"),
                              ("drum", "hat", "Hat"), ("synth", "square", "Square")):
        p.lanes.append(Lane(kind=kind, sound=sound, name=name))
    return p


def demo_project() -> Project:
    """A representative groove that looks like the reference screenshot."""
    import random
    random.seed(7)
    names = [("sample", "My sound"), ("sample", "My sound"), ("sample", "My sound"),
             ("sample", "My sound"), ("drum", "Snare"), ("sample", "My sound"),
             ("sample", "My sound"), ("sample", "My sound"), ("sample", "My sound"),
             ("synth", "Square (hollow)"), ("drum", "Snare"), ("drum", "Tom — mid")]
    p = Project(bpm=90)
    for kind, nm in names:
        lane = Lane(kind=kind, sound=("snare" if kind == "drum" else "square"), name=nm)
        p.lanes.append(lane)
        for k in range(3 + random.randint(0, 3)):
            beat = 4 + k * 3 + random.random() * 2
            length = (0.4 + random.random() * 0.8) if random.random() < 0.3 else 0.0
            p.events.append(Event(lane_id=lane.id, beat=beat, length=length,
                                  src_t=beat * 0.1, src_dur=0.2))
    return p
